language: minimal

sudo: false

matrix:
  fast_finish: true
  include:
    - name: "default"
      env: PY=3.7
    - name: "coding_standards"
      env: PY=3.7

before_install:
  # Install miniconda and create TEST env.
  - |
    wget http://bit.ly/miniconda -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
    conda update conda --quiet
    conda config --add channels conda-forge --force
    conda install pycryptosat
    conda config --set channel_priority strict
    conda config --set safety_checks disabled
    conda create --name TEST python=$PY --file requirements.txt --file requirements-dev.txt
    source activate TEST

install:
  - python setup.py sdist && version=$(python setup.py --version) && pushd dist && pip install nbrr-${version}.tar.gz && popd

script:
  - if [[ $TRAVIS_JOB_NAME == 'default' ]]; then
      cp -r tests/ /tmp ;
      pushd /tmp && pytest -n 2 -rxs tests && popd ;
    fi

  - if [[ $TRAVIS_JOB_NAME == 'coding_standards' ]]; then
      pytest --flake8 -m flake8 ;
    fi

deploy:
  skip_cleanup: true
  provider: pypi
  user: ocefpaf
  password:
    secure: "cwe72B9hIiDFHC6Us3MLLwqxTfgerSnQR1yae4AJpl+zT2KD7/a6TijNqXSgsnfYcorC+tXM/meDHHf/J+OzlBVJa0aenHQZjZyi1zGJmzTxC4elyE1wUvY1S/VGgZ7hJiz5FULQbbwuAF1rI8c6ETXBQNViwKNngpvBz9pQusqE3tA21PLuSoDWkH8OV8mODSoCoW0hA+758QBtRTGBUWx85sG9gPtbr3S8yZ/hDuJZ7FGYfpuNpcBWJkMVyyhsrULk6V0P6JBDZPFpMIkBUXUcZkZZBjey2W/tP7ij2MNhxoyURNYadSO/0XT1nBTMQqLAFo8wfiBbru8GtjaPPPwN94tMYMI4WwhHXdaWYh6V9ccot9uoVXydQPyKwfcHCoG5UvMaxY+rqTB9AdvsxeCH9/exLYeHsJbMetp+AlIiYrbPndqjEsJgF631b5CmfFpOgB8breMZ25ng8wMOXqajrq/dGQVidd4MNrwH+H2KnDyzEBOHXT1Gf/g79VwHfJZ841899swAJQil1yoEDNHsuPHqvAZGs5LQx8wg4IvYBVdtvdn3eBFTwoCPeIVK8XM0e6JopFD300vPQG70kNOiHBEoLuy83QEs3Eriin7/YlJTEHsMV4iDWmFF7Griv2vm8tRtj5BhYNJRlQYT8+PQ/dZe4QZuIDk4Xb8Plxc="
  distributions: sdist bdist_wheel
  upload_docs: no
  on:
    repo: pyoceans/nbrr
    tags: true
    all_branches: master
    condition: '$TRAVIS_JOB_NAME == "default"'
